### ISSUE TITLE
avoid the SuperUser toast every time

### ISSUE THREAD

**Issue by durka** [durka/HallMonitor#13]
It's kind of annoying to see the toast from SuperUser every time the cover is opened. There are two ways I see to fix this low-priority annoyance:
1. [edit] Do nothing, and let the user go into SuperUser and turn off the toasts if they wish.
2. Instead of running a new "su" process every time, just keep the process open from when the service starts. Then we can send it echo commands as needed.
3. Write a little shell script or NDK program that we run when the service starts, and stays open to receive our commands and do the root actions.

3 seems a little more secure, since it still keeps a root-privileged process running, but it's much more restricted in what it will do than a full-fledged "su" shell. Right now, the only commands run are "whoami" and "echo clear_cover_mode..." so the program would be nearly as simple as "cat". But for answering phone calls we will need to run another process ("input") as well, to spoof keystrokes.

I was talking to some people on #android-root and they more or less suggested 3. I didn't even realize 1 was an option until it was pointed out below. It still might be cleaner to have a process/script centralizing the root actions in one place.

**Comment by VolMi** [comment]
What is wrong with the method to tell SuperUser to avoid toasting?
All my root apps toast me by default everytime they do what they do. That's why I open SuperUser and tell it to stay quiet on apps I trust. Is this an enormous burden...?

**Comment by durka** [comment]
I'm just imagining a shell script like this (not tested at all)

```
#!/bin/sh
su
while read command; do
    case "$command" in
        "whoami")
            whoami
            ;;
        "sensitivity on")
            echo clear_cover_mode,1 >/sys/class/sec/tsp/cmd
            ;;
        "sensitivity off")
            echo clear_cover_mode,0 >/sys/class/sec/tsp/cmd
            ;;
        "phone up")
            input keyevent 5
            ;;
        "phone down")
            input keyevent 6
            ;;
        *)
            echo "ERROR: invalid command"
            ;;
    esac
done
```

**Comment by durka** [comment]
Oh I didn't realize you could go into SuperUser and do that! That's probably a better solution anyway.

**Comment by VolMi** [comment]
:)

~~Btw, what do you use root for? I was never asked to allow root for HallMonitor, yet.~~
edit:
silly me, just need to read your script attempt...

**Comment by durka** [comment]
There are some features in the newer versions (unreleased, but I think you are using it already :) ) that require root. They don't happen unless you check the box to enable root in the HM settings.
- boost screen sensitivity when the cover is closed, to enable:
  - killing an alarm that goes off while the cover is closed
  - (in the future) answering/rejecting a call that comes in while the cover is closed
  - (in the future) dismissing a text message that comes in while the cover is closed

Root is required to set the screen sensitivity, and to answer/reject a call. (Not sure about texts yet.) So if it's enabled, then the toast comes up every time the cover is opened, because HM has just lowered the screen sensitivity. But, now I know how to turn that off for myself :)

**Comment by habeIchVergessen** [comment]
closed cover for device GT-I9195 requires following commands to enable touch functionality.

echo module_on_master > /sys/class/sec/tsp/cmd
echo clear_cover_mode,3 > /sys/class/sec/tsp/cmd

otherwise /sys/class/sec/tsp/cmd_result reports

clear_cover_mode,1:NG

**Comment by durka** [comment]
Fascinating! I'll put in a check for the device model and add that. Are you just doing this by trial and error? And have you figured out the commands to change the sensitivity back down to normal? (or "have you forgotten", eh heh heh)

**Comment by habeIchVergessen** [comment]
just took a look at [mxts_sec.c](https://github.com/CyanogenMod/android_kernel_samsung_jf/blob/cm-10.2/drivers/input/touchscreen/mxts_sec.c). sensitivity off works.
