### ISSUE TITLE
phone controls on→off→on

### ISSUE THREAD

**Issue by durka** [durka/HallMonitor#15]
@VolMi wrote:

> Ha, the phone call interaction is seriously cool! The screen is very sensitive, totally nice. Finally, I can use the phone without fiddling with the open cover and smearing the display. :-)
> But it is important to have the default lock screen disabled. Otherwise, I need to press the power button twice (on→off→on) to bring up HallMonitor's notification.

Can you explain? Do you mean, when the phone rings, the screen doesn't come on at first, and the first time you press the power key Hall Monitor doesn't come up?

**Comment by VolMi** [comment]
Ok, say I have
![screenl_patt](https://f.cloud.github.com/assets/1189207/1788013/25fb0a50-6918-11e3-8d4d-a0f61813378b.png)
My S4 mini is laying closed and a call suddenly arrives.
Then, the Screen turns on, but there is no sign of HallMonitor whatsoever. Instead, I see the usual Android-answer-this-call-interface.

Assume I do not open the cover or touch/press anything in this situation. Instead I press `power` (screen off), then `power` again (screen on). Now your controls appear in the S View.

edit:
Tried again, now HallMonitor came up directly. Hmm...

**Comment by durka** [comment]
Hmm. Maybe I could put in some stuff to let you send a debug log somehow. On my phone, when it rings I see the regular phone-ringing screen come up for a second, then Hall Monitor takes over. My other idea is that right now, HM reacts to the event when the phone starts ringing, but it doesn't check the phone state when it's woken up for some other reason. So maybe there is a way to do that.

**Comment by durka** [comment]
I'm closing this but if it's still a problem in latest versions you can re-open it.
