### ISSUE TITLE
Add flashlight control

### ISSUE THREAD

**Issue by Wallace0** [durka/HallMonitor#17]
I've added a new branch from tidy-up with some modifications to add a flashlight control button to the display,

**Comment by durka** [comment]
tidy-up is merged into master

**Comment by durka** [comment]
Merged the flashlight branch as well. I didn't realize that was the stock CM flashlight; that makes it more acceptable to have that dependency. But we could maybe search for it on installation and suggest it, if it's not there.

**Comment by Wallace0** [comment]
OK thanks - I'll create a flashlight2 branch from master and add in an option preference to disable it and I'll also see if I can add a check for the stock flashlight app. I'll also delete the tidy-up, merge and flashlight branches as they aren't needed any more.

PS I did a local merge with the call answer stuff from hVs pull request and I've been running that since last night and it seems to be working pretty nicely.

**Comment by Wallace0** [comment]
I've put the changes for making the torch control optional and also adding a check for the stock flash light app into flashlight2 - it was a new branch from master so should merge straight in.
