### ISSUE TITLE
news: thoughts on 0.1

### ISSUE THREAD

**Issue by durka** [durka/HallMonitor#22]
So, I'm thinking about cutting release 0.1, soon. Meaning, in the next couple of days.

Things that I want to get in for 0.1:
- [x] a little much-needed preference de-complexifying **(in branch _pref-cleanup_)**
- [ ] hIV's code for slide-to-answer/reject phone calls
- [x] notification blacklist
- [ ] fix all the remaining bugs :)

Things that are going to slip to 0.2:
- [ ] more preference de-complexifying
- [x] network indicators **(in branch _signal-indicators_)**
- [ ] hIV's radial context menu
- [ ] rearrangeable DefaultActivity layout
- [ ] code clean-up and refactoring :)

**Comment by Wallace0** [comment]
Yep, I'd agree with that as a good plan. I'm gonna be absolutely slammed for next few weeks though with my day job, but I'll pitch in as and when I can.

**Comment by habeIchVergessen** [comment]
sounds good. i would prefer separated java files for functionality (refer to OptionOverlay in repository TestInput). what do you think about?

**Comment by durka** [comment]
Sorry, @habeIchVergessen, I'm not 100% sure what you're saying.

**Comment by habeIchVergessen** [comment]
i would split the current source code into more files to reduce complexity of merges. an example could be OptionOverlay.java from TestInput repository.

**Comment by durka** [comment]
Yeah, you may be right. Functions.java is getting top-heavy. I wanted to centralize the "business logic" instead of spreading it around the different activities/services but I need to do some refactoring for sure.

**Comment by durka** [comment]
Pushing the network indicators to 0.1.1, I think. They make everything cluttered (see signal-indicators branch) and give me ideas for even more buttons, which means it should wait for the rearrangeable components feature (or a popup menu).
