### ISSUE TITLE
Dies nothing at all on S4

### ISSUE THREAD

**Issue by TauPan** [durka/HallMonitor#36]
I've tried with cm 10 and 11, device is a european jftexx.
Gt i9505, running

**Comment by TauPan** [comment]
sorry, hit submit prematurely.

Cm11-20140311-nightly-jflte.

Not sure what information I cannot provide that would help here. I can easily pull an adb log and send it to you privately, if that helps.

Kind regards
Friedel

**Comment by TauPan** [comment]
s,cannot,can,

**Comment by durka** [comment]
Well, that's unfortunate. I'd love to see an ADB log captured both while you're activating Hall Monitor, and while you open and close the cover.

**Comment by TauPan** [comment]
Ok. This might take a while, since I need to do this at home and I'm currently on my way to work.

**Comment by TauPan** [comment]
Sent logs to the mail address listed in your github profile. Please keep them confidential!

**Comment by manusfreedom** [comment]
Could you try my version 0.3.5?

**Comment by TauPan** [comment]
@manusfreedom I just tried it. It does nothing at all as well. When I close or open the cover, nothing happens. I just see the superuser toast ("superuser has been granted for HallMonitor"). No difference if I set "Real Hall" in root features or not.

**Comment by manusfreedom** [comment]
I personally use:
- GT-I9505 (intl)
- last CM11 nightly (20140618)
- Alucard Kernel AOSP 2.6.8
- SuperSU 2.0

**Comment by TauPan** [comment]
- GT-I9505 (intl)
- last CM11 snapshot (20140609)
- kernel from that snapshot
- SuperSU 2.00 ... When I just started it to check the version, it tried to upgrade the su binary and failed, but I have no problems using SU-Access generally

**Comment by B--B** [comment]
Really strange, seems a problem related to supersu... Have you tried to clean and reinstall supersu? However I ' m testing latest release, everything works fine with real hall sensor. 
My conf 
Paranoid Android 4.4 rc2
Kernel stock
I9505 int jflte 
I have a couple of commits to pull but i' ll wait until all this change will be merged. 
If you need log or something else just ask.

**Comment by manusfreedom** [comment]
Taupan: Please run as root this command and send me it:
getevent -i

**Comment by TauPan** [comment]
I'm back on stock on an S5, my S4 is non-operational, so there's no way I can reproduce this any more. Not going to flash the S5 yet.
