### ISSUE TITLE
Most recent used background app pops up after unlocking screen

### ISSUE THREAD

**Issue by yunyoulu** [durka/HallMonitor#37]
Hi I've been using HallMonitor and it is weird on my phone. When finished using the phone I went back to the Home screen and closed the cover. After HallMonitor turned off the screen as desired, I opened the cover again (and unlock the screen if armed with screen lock) and the last used app popped up, although I was at Home screen before closing the cover.

The last used background app would not appear if the screen was locked manually by pressing the power button other than by closing the cover.

I would be grateful if I can be informed whether this is the way HallMonitor is designed to behave. Sorry I am not familiar with Android programming architecture. After checking the code I noticed that in the implementation of `org.durka.hallmonitor.Functions.open_cover(Context)` method a call of `defaultActivity.moveTaskToBack(true)` was used to hide the UI of HallMonitor. Does this call bring up the 2nd topmost application OTHER THAN the home screen in the activity stack? I'm using CM11 (nightly, oops) on jflte.

I apologize if this post is annoying. Just curious about it.

**Comment by durka** [comment]
I've noticed this. I think that moveTaskToBack needs to be conditional on something. I will look into what the right condition is and put that into the next version (presumably 0.2.2).

**Comment by durka** [comment]
Thanks for the report. Bug reports are useful, not annoying!

**Comment by yunyoulu** [comment]
Thank you. If the cover is quickly closed and opened (without locking the phone) the default activity disappears normally and no other application is brought foreground. The problem only occurs when opening cover from a locked state.

**Comment by MyPublic** [comment]
Same behaviour here with my S4 (CM11).
Sometimes more than one app pops up (Firefox, Stock Browser, Chrome, Dialer). Would be great, if this can be fixed!
@durka Thanks for the great app!!

**Comment by durka** [comment]
I've fixed this in that the most recently used app does not come up anymore. Hall Monitor still sometimes takes a long time to appear when the cover is closed over the home screen, still investigating that. New version should be coming soon to F-Droid.
