### ISSUE TITLE
Flip Cover ?

### ISSUE THREAD

**Issue by wilfried18** [durka/HallMonitor#38]
When will the compatibility of "Flip Cover"?

**Comment by durka** [comment]
What?

**Comment by wilfried18** [comment]
I'm "AOSP rom" and my flip cover does not work even with the application so I ask when there is not such thing for "s-view" but for "flip cover

**Comment by durka** [comment]
Ah, okay. As far as I know, what I call S-View and Flip Cover refer to the same thing. Can I have some more information on what phone you have, what cover, and what version of Android?

**Comment by wilfried18** [comment]
@durka http://www.galaxys4.fr/samsung-galaxy-s4-test-de-la-flip-cover
galaxy s4 gt9505 rom aosp android 4.2.2

**Comment by durka** [comment]
Thanks for that reference. Unfortunately, it seems the flip cover, unlike the view cover, does not have a magnet in it

> Contrairement à la S View Cover, ici aucun capteur à effet Hall n'est présent et de ce fait, lorsque vous ouvrez le rabat, le smartphone ne se déverrouille pas. En revanche, vous pourrez utiliser cette fonctionnalité grâce à l'application Simple Cover Lock ( disponible sur le Play Store ).

so Hall Monitor cannot work with this because it will not trigger the hall effect sensor. Sorry!

**Comment by durka** [comment]
An app like [Simple Cover Lock](https://play.google.com/store/apps/details?id=net.zalio.android.cso&amp;feature=search_result) will use the proximity sensor only so it should work with any cover (or by simply waving your fingers over the proximity LED).

**Comment by wilfried18** [comment]
Tanks @durka damage I liked your open source application
