### ISSUE TITLE
Put our own activity or widget on top of the lockscreen

### ISSUE THREAD

**Issue by durka** [durka/HallMonitor#4]
The default lockscreen, with cLock, happens to have the clock visible through the view cover, and you can kind of see the notification bar, but nothing else. There's a bunch of wasted space above the clock.

S View has a whole different activity that is "on top" of the lockscreen, and is black except for under the view cover. It has a clock and some notifications (email, text) but it's not configurable.

I want to either make an activity like that, or make a lockscreen widget, or enhance cLock, to make better use of the space.

**Comment by durka** [comment]
See `activity` branch: bda39dbbe4. By trial and error I sized a view to the view cover window. But it doesn't have any content yet.

**Comment by durka** [comment]
To turn on screen interaction through the cover:

```
adb shell su -c 'echo clear_cover_mode,1 >/sys/class/sec/tsp/cmd'
```

To turn it off, replace that 1 with a 0.

Source: https://github.com/chenxiaolong/hudson/blob/master/roms/cm-10.2/high-touch-sensitivity/0001-Samsung-add-support-for-high-touch-sensitivity.patch

So far tested on jfltetmo CM10.1.3 and jfltexx CM10.2, so from two samples I conclude that this is the answer :)

**Comment by Wallace0** [comment]
I've created an appwidgets branch, branched from the activity branch. In it I've taken the framework for the full screen windowed display and merged that in with the capability to select 3rd party widgets to display. Note that I renamed ' FullScreenActivity' to 'DefaultActivity' - the 'DefaultActivity' will represent what is displayed when the case is closed or when the power button is pressed when the case is closed (if nothing else supersedes it), and will be differentiated from say the 'AnswerPhoneActivity', 'MediaPlayingActivity' etc. 

Along the way I've added more comments to the code and more debug statements, I've also fixed some lifecycle issues that were in the activities code.

Also note that the way I've implemented the app widget handler will allow us to use it to use 3rd party widgets across all activities if we want.

Next up I'm going to look at providing our own basic clock display as a fall back if no 3rd party widget is selected, and adding in listening for the power button event to then display the default activity.

**Comment by Wallace0** [comment]
Default clock view and display of default activity when the power button is pressed is done (although the clock view is VERY basic and quite ugly and could do with prettying up somewhat)

**Comment by Wallace0** [comment]
Capability to request root access (running whoami as su) added, plus capability to change sensitivity by echo clear_cover_mode,1 >/sys/class/sec/tsp/cmd. Unfortunately this isn't working - the commands run fine and sensitivity does change (as tested by not letting it revert, closing the app and then testing), but it won't work within the context of the app - not sure why yet.

**Comment by Wallace0** [comment]
Fixed the through the window issue, it was actually the Handler.postDelayed call that was interfering with the input for some reason. I switched it to a Timer (and an in-line overridden TimerTask) and it's working now.

**Comment by durka** [comment]
Nice, I like this. I might change up the colors though :)

I see the clipping issue you described with cLock.

I merged master into this so it's up to date with version 0.0.2a. I really hope I haven't caused you merge conflicts!

**Comment by Wallace0** [comment]
Thanks. Yep the colors need tweaking! Could make them configurable easily
enough. I'm done for the night, will do some more tomorrow.

**Comment by Wallace0** [comment]
Just had a look at the master branch and the changes from the appwidgets branch don't seem to be in there - am I missing something?

**Comment by Wallace0** [comment]
I've just committed more changes into appwidgets - lots of general tidy up, I've added loads of comments and a bit more debug. I also fixed some issues with the eventing mechanism - so far as I could tell there was no need for a lot of the stuff in Functions.Events.device_admin_status - it was all duplicating what was happening elsewhere anyway. I also removed the broadcast receiver from the view event service as that's now handled from within DefaultActivity. Initial testing seems to show it working OK for me.

NB: The sony experia clock (free on google play) works nicely as the clock widget, personally I've got he DoggCatcher player in as my default widget for now and that seems to work well.

**Comment by Wallace0** [comment]
Just committed a few more changes - calls to finish have been replaced with moveToBack as that should be more efficient - I've also changed to hide the configuration screen on open_cover as I was finding it liked to pop up. Also changed some logic to fix issue with app crashing if you closed config and then went back in. Initial testing seems to show this is stable now (though I've done all of about 10 minutes worth).

**Comment by durka** [comment]
Sorry, I did the merge but neglected to push it. Now I have, so... let the merges conflict!

**Comment by durka** [comment]
Merged this into master so I can branch off call-widget (to work on the answering the phone part). Feel free to continue working in the branch.

**Comment by Wallace0** [comment]
Cool, figured you might have forgotten to push it! Cool, well if this has gone in to the master then I'll reset to there and look to re-branch again - I think we can close both activities and appwidgets branches. If you are going to look at the phone answering bit, then maybe I'll look at the notifications piece. (though not tonight as I'm about to head out wine tasting! :0)

**Comment by Wallace0** [comment]
Looks like everything has merged nicely into master so I think we can close this issue, and delete the appwidgets and activities branches now. Do you agree? (in which case please do so)

**Comment by durka** [comment]
Okay, reopening this briefly... I noticed an issue where the widget seems frozen. I'm using the Xperia digital clock widget, same as you, but the time never seems to update. Do you have this? (It could also be some change that I made in the notifications branch... perils of dogfooding.) Using the Hall Monitor built in clock, it does have the correct time.

**Comment by Wallace0** [comment]
Sorry should have mentioned it, that's fixed in one of the latest few
commits on the mediacontrols branch. I delegated widget listener control to
HMAppWidgetManager.

**Comment by durka** [comment]
Oh okay cool, I see that commit now.
