### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ChrisCurrin** [durka/HallMonitor#46]
Is it possible to disable the home button when Hall Monitor is active? I sometimes wake the phone to find it in the state arising from the action of the home button. 
Not a major concern, but an annoyance nonetheless. 
P.S. This is for S4mini (CM 11)

**Comment by durka** [comment]
Hmm, this is not generally possible (the OS handles the Home key press and doesn't even tell the app about it) but there maybe something I can do if root access is enabled. I will look into it.

**Comment by ChrisCurrin** [comment]
Thanks man, I use a custom ROM which has root access. Not sure how difficult it would be to implement though

**Comment by durka** [comment]
Well, I spoke too soon. Found a library: https://github.com/shaobin0604/Android-HomeKey-Locker

So this will be in the next version.
